GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/login HTTP/1.1
Content-Type: application/json

{
    "username": "LuisD",
    "password": "123456789"
}
###
POST http://localhost:3003/api/login HTTP/1.1
Content-Type: application/json

{
    "username": "Pedrojuan",
    "password": "123456789"
}
###
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikx1aXNEIiwiaWQiOiI2MWE1NDdmYWI5MTgwOWE4OWU0YmYxZWMiLCJpYXQiOjE2Mzg2Mzc3MjJ9.u1rO98PUFvGmJWvJnYh1olVeckinz5qBDLQiKoinSKo

{
    "title": "DDDDD",
    "author": "Luis4AAAAA44",
    "url": "https://reddiasdasdat.com"
}
###
DELETE http://localhost:3003/api/blogs/61a560e72d21067b07aa705e HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikx1aXNEIiwiaWQiOiI2MWE1NDdmYWI5MTgwOWE4OWU0YmYxZWMiLCJpYXQiOjE2MzgyMjY4NzB9.bIP_7C5YNHbn9_lMMfRzEeXWr0_3iLFpJZdVkQsXhZY

